spring.application.name=Diplom
spring.data.mongodb.uri=mongodb://localhost:27017/diploma

jwt.secret=MyVerySecretKeyForJwtToken12345678901234567890
jwt.expiration=86400000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rkulzabaj@gmail.com
spring.mail.password=xfudebxqilqesevf

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# =========================
# Multipart / File Upload
# =========================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=550MB

# Root folder for uploaded files
app.upload.dir=uploads

# =========================
# Logging
# =========================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO
logging.level.com.diploma.Diplom=DEBUG


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

certificate.storage.path=uploads/certificates
app.base-url=http://localhost:8080
