spring:
  application:
    name: Diplom

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

  data:
    mongodb:
      uri: ${MONGODB_URI}

    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 550MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    com.diploma.Diplom: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

paypal:
  client-id: ${PAYPAL_CLIENT_ID}
  client-secret: ${PAYPAL_CLIENT_SECRET}
  base-url: https://api-m.sandbox.paypal.com
  plan-id: P-58N535868G1027601NHFZDXQ

app:
  upload:
    dir: uploads
  base-url: http://localhost:8080
  certificate:
    storage:
      path: uploads/certificates

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    doc-expansion: list
    disable-swagger-default-url: true

  api-docs:
    path: /v3/api-docs

  group-configs:
    - group: Authentication
      paths-to-match: /auth/**

    - group: Courses
      paths-to-match: /courses/**

    - group: Lessons
      paths-to-match: /lessons/**

    - group: Quizzes
      paths-to-match: /quizzes/**,/quiz-attempts/**

    - group: Progress & Certificates
      paths-to-match: /progress/**,/api/certificates/**

    - group: Enrollments & Payments
      paths-to-match: /enrollments/**,/payments/**,/subscriptions/**

    - group: Teacher Applications
      paths-to-match: /teacher-applications/**