package com.diploma.Diplom.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import io.swagger.v3.oas.annotations.media.Schema;
@Schema(description = "A student's enrollment in a course, including access type and status")
@Data
@Document(collection = "enrollments")
public class Enrollment {

    @Schema(description = "The unique identifier for the enrollment record, generated by MongoDB")
    @Id
    private String id;

    @Schema(description = "The user who is enrolled in the course")
    private String userId;

    @Schema(description = "The course in which the user is enrolled")
    private String courseId;

    @Schema(description = "The type of access the user has to the course (e.g., free, paid, subscription)")
    private AccessType accessType;

    @Schema(description = "The status of the enrollment (e.g., active, expired, cancelled)")
    private EnrollmentStatus status;

    @Schema(description = "The payment identifier associated with the enrollment")
    private String paymentId;

    @Schema(description = "The subscription identifier associated with the enrollment")
    private String subscriptionId;

    @Schema(description = "The date and time when the user enrolled in the course")
    private LocalDateTime enrolledAt;
    
    @Schema(description = "The date and time when the enrollment expires (if applicable)")
    private LocalDateTime expiresAt;
}