package com.diploma.Diplom.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDateTime;

@Schema(description = "A subscription for a course on the platform")
@Data
@Document(collection = "subscriptions")
public class Subscription {
    @Schema(description = "The unique identifier for the subscription record, generated by MongoDB")
    @Id
    private String id;

    @Schema(description = "The user who has subscribed to the course")
    private String userId;

    @Schema(description = "The plan to which the user is subscribed")
    private String planCode; 

    @Schema(description = "The provider for the subscription, e.g. PAYPAL")
    private String provider; 

    @Schema(description = "The ID of the subscription plan in the payment provider's system (e.g. PayPal Plan ID)")
    private String paypalPlanId;

    @Schema(description = "The ID of the subscription in the payment provider's system (e.g. PayPal Subscription ID)")
    private String paypalSubscriptionId;

    @Schema(description = "The status of the subscription, e.g. ACTIVE, CANCELED, PAST_DUE")
    private SubscriptionStatus status;

    @Schema(description = "The timestamp when the subscription started")
    private LocalDateTime startedAt;

    @Schema(description = "The timestamp when the next billing occurs for the subscription")
    private LocalDateTime nextBillingTime;

    @Schema(description = "The timestamp when the subscription ended or was canceled")
    private LocalDateTime endedAt;

    @Schema(description = "The timestamp when the subscription was created", example = "2023-01-01T00:00:00")
    private LocalDateTime createdAt;
    
    @Schema(description = "The timestamp when the subscription was last updated", example = "2023-01-01T00:00:00")
    private LocalDateTime updatedAt;
}