package com.diploma.Diplom.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.time.LocalDateTime;

@Schema(description = "An application submitted by a user to become a teacher on the platform")
@Data
@Document(collection = "teacher_applications")
public class TeacherApplication {
    @Schema(description = "The unique identifier for the teacher application, generated by MongoDB")
    @Id
    private String id;

    @Schema(description = "The ID of the user who submitted the application")
    private String userId;

    @Schema(description = "The full name of the user")
    private String fullName;

    @Schema(description = "The email address of the user")
    private String email;

    @Schema(description = "The specialization of the teacher, e.g. 'Java', 'Python', 'Data Science'")
    private String specialization;

    @Schema(description = "The number of years of experience the teacher has in their specialization")
    private int yearsOfExperience;

    @Schema(description = "A brief description of the teacher's background and qualifications")
    private String resumeText;

    @Schema(description = "The filename of the uploaded resume file, if any")
    private String resumeFileName;

    @Schema(description = "The URL of the uploaded resume file, if any")
    private String resumeFileUrl;

    @Schema(description = "The status of the teacher application, e.g. 'Pending', 'Approved', 'Rejected'")
    private String status;

    @Schema(description = "An optional comment from the reviewer when approving or rejecting the application")
    private String reviewComment;

    @Schema(description = "The score assigned to the application by the reviewer, e.g. 0-100")
    private Integer score;

    @Schema(description = "The timestamp when the application was created", example = "2023-01-01T00:00:00")
    private LocalDateTime createdAt;

    @Schema(description = "The timestamp when the application was last updated", example = "2023-01-01T00:00:00")
    private LocalDateTime updatedAt;

    @Schema(description = "A summary of the application generated by AI")   
    private String aiSummary;

    @Schema(description = "The strengths of the teacher identified by AI")
    private String aiStrengths;

    @Schema(description = "The weaknesses of the teacher identified by AI")
    private String aiWeaknesses;

    @Schema(description = "The recommendations for the teacher identified by AI")
    private String aiRecommendation;

    @Schema(description = "The public ID of the resume file in Cloudinary, if uploaded")
    private String resumePublicId;

    @Schema(description = "The score of the quiz taken by the applicant, if applicable (0-100)")
    private Integer quizScore;      

    @Schema(description = "Whether the applicant passed the quiz based on the passing score threshold")
    private Boolean quizPassed;      
    
    @Schema(description = "The ID of the quiz attempt made by the applicant, if applicable")
    private String quizAttemptId;   
}